stages:
    - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - gem install faraday
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - apt-get update -q
    - apt-get install -y unzip
    - apt-get install -y xvfb
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST

